Config.Weapons = {
  { name = 'WEAPON_KNIFE', label = _U('weapon_knife') },
  { name = 'WEAPON_NIGHTSTICK', label = _U('weapon_nightstick') },
  { name = 'WEAPON_HAMMER', label = _U('weapon_hammer') },
  { name = 'WEAPON_BAT', label = _U('weapon_bat') },
  { name = 'WEAPON_GOLFCLUB', label = _U('weapon_golfclub') },
  { name = 'WEAPON_CROWBAR', label = _U('weapon_crowbar') },
  { name = 'WEAPON_PISTOL', label = _U('weapon_pistol') },
  { name = 'WEAPON_COMBATPISTOL', label = 'Glock' },
  { name = 'WEAPON_APPISTOL', label = _U('weapon_appistol') },
  { name = 'WEAPON_PISTOL50', label = 'Desert Eagle' },
  { name = 'WEAPON_MICROSMG', label = 'UZI' },
  { name = 'WEAPON_SMG', label = _U('weapon_smg') },
  { name = 'WEAPON_ASSAULTSMG', label = _U('weapon_assaultsmg') },
  { name = 'WEAPON_ASSAULTRIFLE', label = 'AK-47' },
  { name = 'WEAPON_CARBINERIFLE', label = 'M4A1' },
  { name = 'WEAPON_ADVANCEDRIFLE', label = 'AUG' },
  { name = 'WEAPON_MG', label = _U('weapon_mg') },
  { name = 'WEAPON_COMBATMG', label = _U('weapon_combatmg') },
  { name = 'WEAPON_PUMPSHOTGUN', label = _U('weapon_pumpshotgun') },
  { name = 'WEAPON_SAWNOFFSHOTGUN', label = _U('weapon_sawnoffshotgun') },
  { name = 'WEAPON_ASSAULTSHOTGUN', label = _U('weapon_sawnoffshotgun_assaultshotgun') },
  { name = 'WEAPON_BULLPUPSHOTGUN', label = _U('weapon_bullpupshotgun') },
  { name = 'WEAPON_STUNGUN', label = _U('weapon_stungun') },
  { name = 'WEAPON_SNIPERRIFLE', label = _U('weapon_sniperrifle') },
  { name = 'WEAPON_HEAVYSNIPER', label = _U('weapon_heavysniper') },
  { name = 'WEAPON_REMOTESNIPER', label = _U('weapon_remotesniper') },
  { name = 'WEAPON_GRENADELAUNCHER', label = _U('weapon_grenadelauncher') },
  { name = 'WEAPON_RPG', label = _U('weapon_rpg') },
  { name = 'WEAPON_STINGER', label = _U('weapon_stinger') },
  { name = 'WEAPON_MINIGUN', label = _U('weapon_minigun') },
  { name = 'WEAPON_GRENADE', label = _U('weapon_grenade') },
  { name = 'WEAPON_STICKYBOMB', label = _U('weapon_stickybomb') },
  { name = 'WEAPON_SMOKEGRENADE', label = _U('weapon_smokegrenade') },
  { name = 'WEAPON_BZGAS', label = _U('weapon_bzgas') },
  { name = 'WEAPON_MOLOTOV', label = _U('weapon_molotov') },
  { name = 'WEAPON_FIREEXTINGUISHER', label = _U('weapon_fireextinguisher') },
  { name = 'WEAPON_PETROLCAN', label = _U('weapon_petrolcan') },
  { name = 'WEAPON_DIGISCANNER', label = _U('weapon_digiscanner') },
  { name = 'WEAPON_BALL', label = _U('weapon_ball') },
  { name = 'WEAPON_SNSPISTOL', label = _U('weapon_snspistol') },
  { name = 'WEAPON_BOTTLE', label = _U('weapon_bottle') },
  { name = 'WEAPON_GUSENBERG', label = _U('weapon_gusenberg') },
  { name = 'WEAPON_SPECIALCARBINE', label = _U('weapon_specialcarbine') },
  { name = 'WEAPON_HEAVYPISTOL', label = 'M1911' },
  { name = 'WEAPON_BULLPUPRIFLE', label = _U('weapon_bullpuprifle') },
  { name = 'WEAPON_DAGGER', label = _U('weapon_dagger') },
  { name = 'WEAPON_VINTAGEPISTOL', label = _U('weapon_vintagepistol') },
  { name = 'WEAPON_FIREWORK', label = _U('weapon_firework') },
  { name = 'WEAPON_MUSKET', label = _U('weapon_musket') },
  { name = 'WEAPON_HEAVYSHOTGUN', label = _U('weapon_heavyshotgun') },
  { name = 'WEAPON_MARKSMANRIFLE', label = _U('weapon_marksmanrifle') },
  { name = 'WEAPON_HOMINGLAUNCHER', label = _U('weapon_hominglauncher') },
  { name = 'WEAPON_PROXMINE', label = _U('weapon_proxmine') },
  { name = 'WEAPON_SNOWBALL', label = _U('weapon_snowball') },
  { name = 'WEAPON_FLAREGUN', label = _U('weapon_flaregun') },
  { name = 'WEAPON_GARBAGEBAG', label = _U('weapon_garbagebag') },
  { name = 'WEAPON_HANDCUFFS', label = _U('weapon_handcuffs') },
  { name = 'WEAPON_COMBATPDW', label = _U('weapon_combatpdw') },
  { name = 'WEAPON_MARKSMANPISTOL', label = _U('weapon_marksmanpistol') },
  { name = 'WEAPON_KNUCKLE', label = _U('weapon_knuckle') },
  { name = 'WEAPON_HATCHET', label = _U('weapon_hatchet') },
  { name = 'WEAPON_RAILGUN', label = _U('weapon_railgun') },
  { name = 'WEAPON_MACHETE', label = _U('weapon_machete') },
  { name = 'WEAPON_MACHINEPISTOL', label = _U('weapon_machinepistol') },
  { name = 'WEAPON_SWITCHBLADE', label = _U('weapon_switchblade') },
  { name = 'WEAPON_REVOLVER', label = _U('weapon_revolver') },
  { name = 'WEAPON_DBSHOTGUN', label = _U('weapon_dbshotgun') },
  { name = 'WEAPON_COMPACTRIFLE', label = 'AK-74' },
  { name = 'WEAPON_AUTOSHOTGUN', label = _U('weapon_autoshotgun') },
  { name = 'WEAPON_BATTLEAXE', label = _U('weapon_battleaxe') },
  { name = 'WEAPON_COMPACTLAUNCHER', label = _U('weapon_compactlauncher') },
  { name = 'WEAPON_MINISMG', label = _U('weapon_minismg') },
  { name = 'WEAPON_PIPEBOMB', label = _U('weapon_pipebomb') },
  { name = 'WEAPON_POOLCUE', label = _U('weapon_poolcue') },
  { name = 'WEAPON_WRENCH', label = _U('weapon_wrench') },
  { name = 'WEAPON_FLASHLIGHT', label = _U('weapon_flashlight') },
  { name = 'GADGET_NIGHTVISION', label = _U('gadget_nightvision') },
  { name = 'GADGET_PARACHUTE', label = _U('gadget_parachute') },
  { name = 'WEAPON_BRIEFCASE', label = 'Briefcase' },
  { name = 'WEAPON_DOUBLEACTION', label = 'Double Action Revolver' },
  { name = 'WEAPON_PISTOL_MK2', label = 'Pistol Mk2' },
  { name = 'WEAPON_SNSPISTOL_MK2', label = 'SNS Pistol Mk2' },
  { name = 'WEAPON_REVOLVER_MK2', label = 'Revolver Mk2' },
  { name = 'WEAPON_SMG_MK2', label = 'SMG Mk2' },
  { name = 'WEAPON_COMBATMG_MK2', label = 'Combat MG Mk2' },
  { name = 'WEAPON_ASSAULTRIFLE_MK2', label = 'Assault Rifle Mk2' },
  { name = 'WEAPON_CARBINERIFLE_MK2', label = 'Carbine Rifle Mk2' },
  { name = 'WEAPON_SPECIALCARBINE_MK2', label = 'Special Carbine Mk2' },
  { name = 'WEAPON_BULLPUPRIFLE_MK2', label = 'Bullpup Rifle Mk2' },
  { name = 'WEAPON_HEAVYSNIPER_MK2', label = 'Heavy Sniper Mk2' },
  { name = 'WEAPON_MARKSMANRIFLE_MK2', label = 'Marksman Rifle Mk2' },
  { name = 'WEAPON_PUMPSHOTGUN_MK2', label = 'Pump Shotgun MK2' },
  { name = 'WEAPON_STONE_HATCHET', label = 'Stone Hatchet' },

  -- Addon Weapons
  { name = 'WEAPON_MK18', label = 'MK18' },
  { name = 'WEAPON_M4A1', label = 'M4A1' },
  { name = 'WEAPON_G36C', label = 'G36C' },
  { name = 'WEAPON_MP5', label = 'MP5A5' },
  { name = 'WEAPON_AK47', label = 'AK-47' },
  { name = 'WEAPON_DRACO', label = 'AKM-S' },
  { name = 'WEAPON_M1911', label = 'M1911' },
  { name = 'WEAPON_L96A3', label = 'L96A3' },
  { name = 'WEAPON_UZI', label = 'Mini UZI' },
  { name = 'WEAPON_M9', label = 'M9 Beretta' },
  { name = 'WEAPON_GLOCK17', label = 'Glock 17' },
  { name = 'WEAPON_DEAGLE', label = 'Desert Eagle' },
  { name = 'WEAPON_BERETTA92', label = 'Beretta 92' },
  { name = 'WEAPON_TOKAREV', label = 'Tokarev TT-33' },
  { name = 'WEAPON_COLTJUNIOR', label = 'Colt Junior' },
  { name = 'WEAPON_MOSSBERG590', label = 'Mossberg 590' },
  { name = 'WEAPON_REMINGTON870', label = 'Remington 870' },
  { name = 'WEAPON_HUNTINGRIFLE', label = 'Hunting Rifle' },
  { name = 'WEAPON_PAINTBALLGUN', label = 'Paintball Gun' },
  { name = 'WEAPON_SAWNOFF', label = 'Sawed-Off Remington M870' },
  { name = 'WEAPON_NONLETHALSHOTGUN', label = 'Bean Bag Shotgun' },
}