CreateThread(function()
    AddTextEntry("WT_M4A1", "M4A1")
    AddTextEntry("WT_G36C", "G36C")
    AddTextEntry("WT_MP5", "MP5A5")
    AddTextEntry("WT_AK47", "AK-47")
    AddTextEntry("WT_M1911", "M1911")
    AddTextEntry("WT_L96A3", "L96A3")
    AddTextEntry("WT_DRACO", "AKM-S")
    AddTextEntry("WT_UZI", "Mini UZI")
    AddTextEntry("WT_M9", "M9 Beretta")
    AddTextEntry("WT_GLOCK17", "Glock 17")
    AddTextEntry("WT_DEAGLE", "Desert Eagle")
    AddTextEntry("WT_BERETTA92", "Beretta 92")
    AddTextEntry("WT_TOKAREV", "Tokarev TT-33")
    AddTextEntry("WT_HUNTING", "Hunting Rifle")
    AddTextEntry("WT_COLTJUNIOR", "Colt Junior")
    AddTextEntry("WT_MOSSBERG590", "Mossberg 590")
    AddTextEntry("WT_REMINGTON870", "Remington 870")
    AddTextEntry("WT_PAINTBALLGUN", "Paintball Gun")
    AddTextEntry("WT_SG_NONLETHAL", "Bean Bag Shotgun")
    AddTextEntry("WT_SAWNOFFM870", "Sawed-Off Remington M870")
    AddTextEntry("WT_MK18", "Daniel Defense MK18")
end)