Config.WalkStyles = {
	Default = "move_m@multiplayer",
	Femme = "move_f@femme@",
	Down = "move_m@sad@a",
	Fancy = "move_m@money",
	Sassy = "move_f@sassy",
	Coward = "move_m@coward",
	Brave = "move_m@brave@a",
	Buzzed = "move_m@buzzed",
	Female = "move_f@heels@c",
	Casual = "move_m@casual@a",
	Casual1 = "move_m@casual@b",
	Casual2 = "move_m@casual@c",
	Casual3 = "move_m@casual@d",
	Casual4 = "move_m@casual@e",
	Casual5 = "move_m@casual@f",
	Homeless = "move_m@hobo@a",
	Overweight = "move_m@fat@a",
	Hipster = "move_m@hipster@a",
	Muscular = "move_m@muscle@a",
	Shocked = "move_m@shocked@a",
	Hurry = "move_m@hurry_butch@a",
	Confident = "move_m@confident",
	Business = "move_m@business@a",
	Business1 = "move_m@business@b",
	Business2 = "move_m@business@c",
	Intimidated = "move_m@hurry@a",
	Gangster = "move_m@shadyped@a",
	Gangster2 = "move_m@gangster@var_e",
	Gangster3 = "move_m@gangster@var_i",
	Arrogant = "move_f@arrogant@a",
	Depressed = "move_m@depressed@a",
	Chill = "move_f@depressed@a",
	Frantic = "move_m@quick",
	Homosexual = "move_f@maneater",
	Swagger = "move_m@swagger@b",
	Sexy = "move_f@sexy@a",
	Posh = "move_m@posh@",
	Sneaking = "move_stealth@p_m_two@unarmed@core",
	Party = "anim@move_m@grooving@",
	Party2 = "anim@move_m@grooving@slow@",
	Michael = "move_p_m_zero",
	Trevor = "move_p_m_two",
	Jimmy = "move_characters@Jimmy@slow@",
	Scared = "move_f@scared",
	-- bag = "move_m@bag",
	-- case = "MOVE_P_M_ONE_BRIEFCASE",
}

Config.Animactions = {
	GrabCash = {
		lib = 'anim@heists@ornate_bank@grab_cash',
		anim = 'grab',
		loop = false,
		movable = false
	},
	InCuffs = {
		lib = "mp_arresting",
		anim = "idle",
		movable = true,
		isCuffs = true
	},
	Unholster = {
		lib = "reaction@intimidation@1h",
		anim = "intro",
		movable = true,
		isCuffs = false
	},
	Holster = {
		lib = "reaction@intimidation@1h",
		anim = "outro",
		movable = true,
		isCuffs = false
	},
}

Config.Animations = {
	-- {
	-- 	label = 'Dev',
	-- 	items = {
	-- 		-- {label = "Cuff", type = "anim", data = {lib = "mp_arresting", anim = "idle", movable = true}},
	-- 		{label = "Unholster Wep", type = "anim", data = {lib = "reaction@intimidation@1h", anim = "intro", movable = true}},

	-- 		{label = "Holster Wep", type = "anim", data = {lib = "reaction@intimidation@1h", anim = "outro", movable = true}},

	-- 		{label = "Shoot Self", type = "anim", data = {lib = "mp_suicide", anim = "pistol"}},
	-- 		{label = "Crawl", type = "anim", data = {lib = "move_crawl", anim = "onfront_fwd", movable = true}},

	-- 		{label = "Cuffed", type = "anim", data = {lib = "mp_arresting", anim = "idle", movable = true}},

	-- 		{label = "finger", type = "anim", data = {lib = "mp_player_int_upperfinger", anim = "mp_player_int_finger_02", movable = true}},

	-- 		{label = "drill", type = "anim", data = {lib = "anim@heists@fleeca_bank@drilling", anim = "intro", movable = false}},

	-- 		-- ("mp_player_int_upperfinger", "mp_player_int_finger_02", 2, 750, true, 1);
 --                    -- Wait(750);
 --                    -- Game.Player.Character.Task.PlayAnimation("mp_player_int_upperfinger", "mp_player_int_finger_02_exit", 2, 750, true, 1);

	-- 	}
	-- },
	{
		label = 'Female ONLY',
		female = true,
		items = {
			{label = "Start Race", type = "anim", data = {lib = "random@street_race", anim = "grid_girl_race_start"}},
		}
	},
	{
		label = 'Idles',
		items = {
			{label = "Nod Off", type = "anim", data = {lib = "mp_sleep", anim = "sleep_loop"}},
			{label = "Lean", type = "scenario", data = {anim = "world_human_leaning"}},
			{label = "Guard", type = "scenario", data = {anim = "WORLD_HUMAN_GUARD_PATROL"}},
			{label = "Hang Out", type = "scenario", data = {anim = "WORLD_HUMAN_HANG_OUT_STREET"}},
			{label = "Charming", type = "anim", data = {lib = "mini@strip_club@idles@stripper", anim = "stripper_idle_02"}},
			{label = "Cross Arms", type = "anim", data = {lib = "amb@world_human_cop_idles@female@idle_b", anim = "idle_e"}},
			{label = "Smoking", type = "scenario", data = {anim = "WORLD_HUMAN_SMOKING"}},
			{label = "Smoking (Flirting)", type = "scenario", data = {anim = "WORLD_HUMAN_PROSTITUTE_HIGH_CLASS"}},
			{label = "Drink Coffee", type = "scenario", data = {anim = "WORLD_HUMAN_AA_COFFEE"}},
		   
			{label = "Stand By", type = "scenario", data = {anim = "WORLD_HUMAN_COP_IDLES"}},
			{label = "Hold Belt", type = "scenario", data = {anim = "WORLD_HUMAN_GUARD_STAND"}},

			{label = "Impatient", type = "scenario", data = {anim = "WORLD_HUMAN_STAND_IMPATIENT"}},
			{label = "Impatient 2", type = "scenario", data = {anim = "WORLD_HUMAN_STAND_IMPATIENT_UPRIGHT"}},
			
			{label = "Lay on Side", type = "anim", data = {lib = "amb@world_human_bum_slumped@male@laying_on_right_side@idle_a", anim = "idle_a"}},
			{label = "Lay on Back", type = "scenario", data = {anim = "WORLD_HUMAN_SUNBATHE_BACK"}},
			{label = "Lay on Stomache", type = "scenario", data = {anim = "WORLD_HUMAN_SUNBATHE"}},
			
			{label = "Sunbathe (Front)", type = "scenario", data = {anim = "WORLD_HUMAN_SUNBATHE"}},
			{label = "Sunbathe (Back)", type = "scenario", data = {anim = "WORLD_HUMAN_SUNBATHE_BACK"}},
			
			{label = "Sit (Bench)", type = "scenario", data = {anim = "PROP_HUMAN_SEAT_BENCH"}},
			-- {label = "Sit (Beer)", type = "scenario", data = {anim = "PROP_HUMAN_SEAT_BENCH_DRINK_BEER"}},
			-- {label = "Sit (Food)", type = "scenario", data = {anim = "PROP_HUMAN_SEAT_BENCH_FOOD"}},
			-- {label = "Sit (Coffee)", type = "scenario", data = {anim = "PROP_HUMAN_SEAT_BENCH_DRINK"}},
			{label = "Sit (Waiting)", type = "scenario", data = {anim = "PROP_HUMAN_SEAT_BUS_STOP_WAIT"}},
			{label = "Sit (Admiring)", type = "scenario", data = {anim = "PROP_HUMAN_SEAT_STRIP_WATCH"}},
			{label = "Sit (Ground)", type = "scenario", data = {anim = "WORLD_HUMAN_PICNIC"}},
			-- {label = "Sit (Against Wall)", type = "scenario", data = {anim = "WORLD_HUMAN_STUPOR"}},
			{label = "Sit (Chair)", type = "scenario", data = {anim = "PROP_HUMAN_SEAT_CHAIR"}},
			{label = "Sit (Arm Chair)", type = "scenario", data = {anim = "PROP_HUMAN_SEAT_ARMCHAIR"}},
			{label = "Sit (Chair Upright)", type = "scenario", data = {anim = "PROP_HUMAN_SEAT_CHAIR_UPRIGHT"}},
			{label = "Sit (Chair MP)", type = "scenario", data = {anim = "PROP_HUMAN_SEAT_CHAIR_MP_PLAYER"}},
			-- {label = "Sit (Wall)", type = "scenario", data = {anim = "WORLD_HUMAN_SEAT_WALL"}},
			-- {label = "Sit (Steps)", type = "scenario", data = {anim = "WORLD_HUMAN_SEAT_STEPS"}},
			-- {label = "Sit (Ledge)", type = "scenario", data = {anim = "WORLD_HUMAN_SEAT_LEDGE"}},
		}
	},
	{
		label = 'Gestures',
		items = {
			{label = "Blow Kiss (female)", type = "anim", data = {lib = "anim@mp_player_intcelebrationfemale@finger_kiss", anim = "finger_kiss"}},
			{label = "Blow Kiss (male)", type = "anim", data = {lib = "anim@mp_player_intcelebrationmale@blow_kiss", anim = "blow_kiss"}},
			{label = "More Kisses", type = "anim", data = {lib = "anim@mp_player_intcelebrationmale@finger_kiss", anim = "finger_kiss"}},
			{label = "Sad (Ground)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@lo_alone@", anim = "lowalone_dlg_gotochurch_laz"}},
			{label = "Gang Sign 1", type = "anim", data = {lib = "mp_player_int_uppergang_sign_a", anim = "mp_player_int_gang_sign_a", movable = true}},
			{label = "Gang Sign 2", type = "anim", data = {lib = "mp_player_int_uppergang_sign_b", anim = "mp_player_int_gang_sign_b", movable = true}},
			{label = "Wank", type = "anim", data = {lib = "anim@mp_player_intcelebrationmale@wank", anim = "wank"}},
			{label = "Flip Off", type = "anim", data = {lib = "mp_player_int_upperfinger", anim = "mp_player_int_finger_01_enter", movable = true}},
			{label = "Jerk Off", type = "anim", data = {lib = "mp_player_int_upperwank", anim = "mp_player_int_wank_01", movable = true}},
			{label = "Slow Clap", type = "anim", data = {lib = "anim@mp_player_intcelebrationmale@slow_clap", anim = "slow_clap", movable = true}},
			{label = "Grab Crotch", type = "anim", data = {lib = "mp_player_int_uppergrab_crotch", anim = "mp_player_int_grab_crotch"}},
			{label = "Bring It On", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_bring_it_on"}},
			{label = "Air Thrusting", type = "anim", data = {lib = "anim@mp_player_intcelebrationfemale@air_shagging", anim = "air_shagging"}},
			{label = "Prepare to Fight", type = "anim", data = {lib = "anim@deathmatch_intros@unarmed", anim = "intro_male_unarmed_e"}},
			{label = "What Have I Done?", type = "anim", data = {lib = "oddjobs@assassinate@multi@", anim = "react_big_variations_a", movable = true}},
		}
	},
	{
		label = 'Greetings',
		items = {
			{label = "Hug", type = "anim", data = {lib = "mp_ped_interaction", anim = "hugs_guy_a"}},
			{label = "Wave", type = "anim", data = {lib = "random@gang_intimidation@", anim = "001445_01_gangintimidation_1_female_wave_loop"}},
			{label = "Greet", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_hello"}},
			{label = "Handshake", type = "anim", data = {lib = "mp_common", anim = "givetake1_a"}},
			{label = "Military Salute", type = "anim", data = {lib = "mp_player_int_uppersalute", anim = "mp_player_int_salute"}},
		}
	},
	{
		label = 'Interactions',
		items = {
			{label = "Peace", type = "anim", data = {lib = "mp_player_int_upperv_sign", anim = "mp_player_int_v_sign"}},
			{label = "Sad", type = "anim", data = {lib = "amb@world_human_bum_standing@depressed@idle_a", anim = "idle_a"}},
			{label = "Yes", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_point"}},
			{label = "Damn", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_damn"}},
			{label = "Cower", type = "anim", data = {lib = "amb@code_human_cower_stand@male@react_cowering", anim = "base_right"}},
			{label = "Dazed", type = "anim", data = {lib = "amb@world_human_bum_standing@drunk@idle_a", anim = "idle_a", movable = true}},
			{label = "Thanks", type = "anim", data = {lib = "mp_action", anim = "thanks_male_06"}},
			{label = "Embrace", type = "anim", data = {lib = "mp_ped_interaction", anim = "kisses_guy_a"}},
			{label = "Twitchy", type = "anim", data = {lib = "amb@world_human_bum_standing@twitchy@idle_a", anim = "idle_a", movable = true}},
			{label = "Facepalm", type = "anim", data = {lib = "anim@mp_player_intcelebrationmale@face_palm", anim = "face_palm", movable = true}},
			{label = "Cheering", type = "anim", data = {lib = "amb@world_human_cheering@female_a", anim = "base"}},
			{label = "Clapping", type = "anim", data = {lib = "amb@world_human_cheering@male_a", anim = "base"}},
			{label = "Calm Down", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_easy_now"}},
			{label = "Come Here", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_come_here_soft"}}, 
			{label = "Flaunting", type = "scenario", data = {anim = "WORLD_HUMAN_PROSTITUTE_LOW_CLASS"}},
			{label = "Congratulate", type = "scenario", data = {anim = "WORLD_HUMAN_CHEERING"}},
			{label = "Point to Self", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_me"}},
		}
	},
	{
		label = 'Job Interactions',
		items = {
			{label = "Notepad", type = "scenario", data = {anim = "CODE_HUMAN_MEDIC_TIME_OF_DEATH"}},
			{label = "Clipboard", type = "scenario", data = {anim = "WORLD_HUMAN_CLIPBOARD"}},
			-- {label = "Hammering", type = "scenario", data = {anim = "WORLD_HUMAN_HAMMERING"}},
			-- {label = "Load Cargo", type = "anim", data = {lib = "mp_am_hold_up", anim = "purchase_beerbox_shopkeeper"}},
			{label = "Investigate Ground", type = "anim", data = {lib = "amb@code_human_police_investigate@idle_b", anim = "idle_f"}},
			{label = "Investigate Surrounding", type = "scenario", data = {anim = "CODE_HUMAN_POLICE_INVESTIGATE"}},
			{label = "Repair Motor", type = "anim", data = {lib = "mini@repair", anim = "fixing_a_ped"}},
			{label = "Direct Traffic", type = "scenario", data = {anim = "WORLD_HUMAN_CAR_PARK_ATTENDANT"}},
			{label = "Shine Flashlight", type = "scenario", data = {anim = "WORLD_HUMAN_SECURITY_SHINE_TORCH"}},
			{label = "Medical Investigation", type = "scenario", data = {anim = "CODE_HUMAN_MEDIC_KNEEL"}},
			-- {label = "Repair Under Vehicle", type = "scenario", data = {anim = "world_human_vehicle_mechanic"}},
			{label = "High Class Prostitute", type = "scenario", data = {anim = "WORLD_HUMAN_PROSTITUTE_HIGH_CLASS"}},
		}
	},
	{
		label = 'Club Dances',
		items = {
			{label = "Male Dancer (1)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim = "high_center"}},
			{label = "Male Dancer (2)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim = "high_center_down"}},
			{label = "Male Dancer (3)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim = "high_center_up"}},
			{label = "Male Dancer (4)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim = "high_left"}},
			{label = "Male Dancer (5)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim = "high_left_down"}},
			{label = "Male Dancer (6)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim = "high_left_up"}},
			{label = "Male Dancer (7)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim = "high_right"}},
			{label = "Male Dancer (8)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim = "high_right_down"}},
			{label = "Male Dancer (9)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim = "high_right_up"}},
			{label = "Male Dancer (10)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim = "low_center"}},
			{label = "Male Dancer (11)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim = "low_center_down"}},
			{label = "Male Dancer (12)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim = "low_center_up"}},
			{label = "Male Dancer (13)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim = "low_left"}},
			{label = "Male Dancer (14)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim = "low_left_down"}},
			{label = "Male Dancer (15)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim = "low_left_up"}},
			{label = "Male Dancer (16)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim = "low_right"}},
			{label = "Male Dancer (17)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim = "low_right_down"}},
			{label = "Male Dancer (18)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim = "low_right_up"}},
			{label = "Male Dancer (19)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim = "med_center"}},
			{label = "Male Dancer (20)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim = "med_center_down"}},
			{label = "Male Dancer (21)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim = "med_center_up"}},
			{label = "Male Dancer (22)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim = "med_left"}},
			{label = "Male Dancer (23)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim = "med_left_down"}},
			{label = "Male Dancer (24)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim = "med_left_up"}},
			{label = "Male Dancer (25)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim = "med_right"}},
			{label = "Male Dancer (26)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim = "med_right_down"}},
			{label = "Male Dancer (27)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim = "med_right_up"}},

			{label = "Female Dancer (1)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "high_center"}},
			{label = "Female Dancer (2)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "high_center_down"}},
			{label = "Female Dancer (3)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "high_center_up"}},
			{label = "Female Dancer (4)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "high_left"}},
			{label = "Female Dancer (5)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "high_left_down"}},
			{label = "Female Dancer (6)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "high_left_up"}},
			{label = "Female Dancer (7)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "high_right"}},
			{label = "Female Dancer (8)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "high_right_down"}},
			{label = "Female Dancer (9)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "high_right_up"}},
			{label = "Female Dancer (10)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "low_center"}},
			{label = "Female Dancer (11)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "low_center_down"}},
			{label = "Female Dancer (12)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "low_center_up"}},
			{label = "Female Dancer (13)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "low_left"}},
			{label = "Female Dancer (14)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "low_left_down"}},
			{label = "Female Dancer (15)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "low_left_up"}},
			{label = "Female Dancer (16)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "low_right"}},
			{label = "Female Dancer (17)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "low_right_down"}},
			{label = "Female Dancer (18)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "low_right_up"}},
			{label = "Female Dancer (19)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "med_center"}},
			{label = "Female Dancer (20)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "med_center_down"}},
			{label = "Female Dancer (21)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "med_center_up"}},
			{label = "Female Dancer (22)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "med_left"}},
			{label = "Female Dancer (23)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "med_left_down"}},
			{label = "Female Dancer (24)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "med_left_up"}},
			{label = "Female Dancer (25)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "med_right"}},
			{label = "Female Dancer (26)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "med_right_down"}},
			{label = "Female Dancer (27)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "med_right_up"}},

			{label = "Dance (Madonna Club 1)", type = "anim", data = {lib = "anim@amb@nightclub@djs@black_madonna@", anim = "dance_b_idle_a_blamadon"}},
			{label = "Dance (Madonna Club 2)", type = "anim", data = {lib = "anim@amb@nightclub@djs@black_madonna@", anim = "dance_b_idle_b_blamadon"}},
			{label = "Dance (Madonna Club 3)", type = "anim", data = {lib = "anim@amb@nightclub@djs@black_madonna@", anim = "dance_b_idle_c_blamadon"}},
			{label = "Dance (Madonna Club 4)", type = "anim", data = {lib = "anim@amb@nightclub@djs@black_madonna@", anim = "dance_b_idle_d_blamadon"}},

			{label = "Dance (Madonna Club 5)", type = "anim", data = {lib = "anim@amb@nightclub@djs@black_madonna@", anim = "dance_b_loop_blamadon"}},

			{label = "Dance (Lazlow Dancefloor 1)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_dancefloor@", anim = "crowddance_hi_06_base_laz"}},
			{label = "Dance (Lazlow Dancefloor 2)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_dancefloor@", anim = "crowddance_hi_06_base_v2_laz"}},
			{label = "Dance (Lazlow Dancefloor 3)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_dancefloor@", anim = "crowddance_hi_11_handup_laz"}},
			{label = "Dance (Lazlow Dancefloor 4)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_dancefloor@", anim = "crowddance_hi_11_raiseup_laz"}},
			{label = "Dance (Lazlow Dancefloor 5)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_dancefloor@", anim = "crowddance_hi_13_shimmyhump_laz"}},
			{label = "Dance (Lazlow Dancefloor 6)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_dancefloor@", anim = "crowddance_hi_13_suckit_laz"}},
			{label = "Dance (Lazlow Dancefloor 7)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_dancefloor@", anim = "crowddance_hi_15_buckingbronco_laz"}},
			{label = "Dance (Lazlow Dancefloor 8)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_dancefloor@", anim = "crowddance_hi_15_shimmyya_laz"}},
			{label = "Dance (Lazlow Dancefloor 9)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_dancefloor@", anim = "crowddance_hi_17_highhorse_laz"}},
			{label = "Dance (Lazlow Dancefloor 10)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_dancefloor@", anim = "crowddance_hi_17_highhorse_laz"}},
			{label = "Dance (Lazlow Dancefloor 11)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_dancefloor@", anim = "crowddance_hi_17_spinaround_laz"}},
			{label = "Dance (Lazlow Dancefloor 12)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_dancefloor@", anim = "crowddance_mi_06_base_laz"}},
			{label = "Dance (Lazlow Dancefloor 13)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_dancefloor@", anim = "crowddance_mi_11_spankthat_laz"}},
			{label = "Dance (Lazlow Dancefloor 14)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_dancefloor@", anim = "crowddance_mi_13_baselong_laz"}},
			{label = "Dance (Lazlow Dancefloor 15)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_dancefloor@", anim = "crowddance_mi_13_lookaround_laz"}},
			{label = "Dance (Lazlow Dancefloor 16)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_dancefloor@", anim = "crowddance_mi_15_handsup_laz"}},
			{label = "Dance (Lazlow Dancefloor 17)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_dancefloor@", anim = "crowddance_mi_15_raiseup_laz"}},
			{label = "Dance (Lazlow Dancefloor 18)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_dancefloor@", anim = "crowddance_mi_17_buckingbronco_laz"}},
			{label = "Dance (Lazlow Dancefloor 19)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_dancefloor@", anim = "crowddance_mi_17_talking_laz"}},
			{label = "Dance (Lazlow Dancefloor 20)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_dancefloor@", anim = "dancecrowd_hi_05_dlg_cuberoot_laz"}},
			{label = "Dance (Lazlow Dancefloor 21)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_dancefloor@", anim = "dancecrowd_hi_05_dlg_havingit_laz"}},
			{label = "Dance (Lazlow Dancefloor 22)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_dancefloor@", anim = "dancecrowd_hi_05_dlg_highaf_laz"}},
			{label = "Dance (Lazlow Dancefloor 23)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_dancefloor@", anim = "dancecrowd_hi_05_dlg_ridegurl_laz"}},
			{label = "Dance (Lazlow Dancefloor 24)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_dancefloor@", anim = "dancecrowd_hi_07_dlg_back288_laz"}},
			{label = "Dance (Lazlow Dancefloor 25)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_dancefloor@", anim = "dancecrowd_hi_07_dlg_whooyeeha_laz"}},
			{label = "Dance (Lazlow Dancefloor 26)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_dancefloor@", anim = "dancecrowd_hi_11_dlg_specialk_laz"}},
			{label = "Dance (Lazlow Dancefloor 27)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_dancefloor@", anim = "dancecrowd_li_06_base_laz"}},
			{label = "Dance (Lazlow Dancefloor 28)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_dancefloor@", anim = "dancecrowd_li_06_base_v2_laz"}},
			{label = "Dance (Lazlow Dancefloor 29)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_dancefloor@", anim = "dancecrowd_li_11_hu_shimmy_laz"}},
			{label = "Dance (Lazlow Dancefloor 30)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_dancefloor@", anim = "dancecrowd_li_11_shimmy_laz"}},
			{label = "Dance (Lazlow Dancefloor 31)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_dancefloor@", anim = "dancecrowd_li_13_holdhead_laz"}},
			{label = "Dance (Lazlow Dancefloor 32)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_dancefloor@", anim = "dancecrowd_li_13_smackthat_laz"}},
			{label = "Dance (Lazlow Dancefloor 33)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_dancefloor@", anim = "dancecrowd_li_15_handup_laz"}},
			{label = "Dance (Lazlow Dancefloor 34)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_dancefloor@", anim = "dancecrowd_li_15_pethorse_laz"}},
			{label = "Dance (Lazlow Dancefloor 35)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_dancefloor@", anim = "dancecrowd_li_17_headtrophy_laz"}},
			{label = "Dance (Lazlow Dancefloor 36)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_dancefloor@", anim = "dancecrowd_li_17_poledance_laz"}},

			{label = "Dance (Lazlow Podium 1)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_hi_06_base_laz"}},
			{label = "Dance (Lazlow Podium 2)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_hi_06_base_v2_laz"}},
			{label = "Dance (Lazlow Podium 3)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_hi_11_buttwiggle_b_laz"}},
			{label = "Dance (Lazlow Podium 4)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_hi_11_buttwiggle_f_laz"}},
			{label = "Dance (Lazlow Podium 5)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_hi_11_takebreath_laz"}},
			{label = "Dance (Lazlow Podium 6)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_hi_11_turnaround_laz"}},
			{label = "Dance (Lazlow Podium 7)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_hi_13_crotchgrab_laz"}},
			{label = "Dance (Lazlow Podium 8)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_hi_13_flyingv_laz"}},
			{label = "Dance (Lazlow Podium 9)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_hi_15_crazyrobot_laz"}},
			{label = "Dance (Lazlow Podium 10)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_hi_15_lookaround_laz"}},
			{label = "Dance (Lazlow Podium 11)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_hi_17_smackthat_laz"}},
			{label = "Dance (Lazlow Podium 12)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_hi_17_spiderman_laz"}},
			{label = "Dance (Lazlow Podium 13)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_li_06_base_laz"}},
			{label = "Dance (Lazlow Podium 14)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_li_06_base_v2_laz"}},
			{label = "Dance (Lazlow Podium 15)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_li_07_fakedrop_laz"}},
			{label = "Dance (Lazlow Podium 16)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_li_11_bigbase_laz"}},
			{label = "Dance (Lazlow Podium 17)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_li_11_pointcrowd_laz"}},
			{label = "Dance (Lazlow Podium 18)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_li_11_takebreath_laz"}},
			{label = "Dance (Lazlow Podium 19)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_li_13_hipswivel_laz"}},
			{label = "Dance (Lazlow Podium 20)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_li_13_turnaround_laz"}},
			{label = "Dance (Lazlow Podium 21)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_li_15_flyingv_laz"}},
			{label = "Dance (Lazlow Podium 22)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_li_15_sexygrind_laz"}},
			{label = "Dance (Lazlow Podium 23)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_li_17_ethereal_laz"}},
			{label = "Dance (Lazlow Podium 24)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_li_17_watupcrowd_laz"}},
			{label = "Dance (Lazlow Podium 25)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_mi_06_base_v1_laz"}},
			{label = "Dance (Lazlow Podium 26)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_mi_06_base_v2_laz"}},
			{label = "Dance (Lazlow Podium 27)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_mi_09_pointdj_l_laz"}},
			{label = "Dance (Lazlow Podium 28)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_mi_09_pointdj_r_laz"}},
			{label = "Dance (Lazlow Podium 29)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_mi_11_hippain_laz"}},
			{label = "Dance (Lazlow Podium 30)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_mi_11_pointthrust_laz"}},
			{label = "Dance (Lazlow Podium 31)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_mi_11_simplepoint_laz"}},
			{label = "Dance (Lazlow Podium 32)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_mi_11_takebreath_laz"}},
			{label = "Dance (Lazlow Podium 33)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_mi_13_enticing_laz"}},
			{label = "Dance (Lazlow Podium 34)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_mi_13_turnaround_laz"}},
			{label = "Dance (Lazlow Podium 35)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_mi_15_robot_laz"}},
			{label = "Dance (Lazlow Podium 36)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_mi_15_shimmy_laz"}},
			{label = "Dance (Lazlow Podium 37)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_mi_17_crotchgrab_laz"}},
			{label = "Dance (Lazlow Podium 38)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_mi_17_teapotthrust_laz"}},
		}
	},
	{
		label = 'Dances',
		items = {
			{label = "Strip Tease 1", type = "anim", data = {lib = "mini@strip_club@lap_dance@ld_girl_a_song_a_p1", anim = "ld_girl_a_song_a_p1_f"}},
			{label = "Strip Tease 2", type = "anim", data = {lib = "mini@strip_club@private_dance@part2", anim = "priv_dance_p2"}},
			{label = "Shake Chest", type = "anim", data = {lib = "mini@strip_club@backroom@", anim = "stripper_b_backroom_idle_b"}},
			{label = "Twerking", type = "anim", data = {lib = "mini@strip_club@private_dance@part3", anim = "priv_dance_p3"}},
			{label = "Drinking Beer", type = "scenario", data = {anim = "WORLD_HUMAN_DRINKING"}},
			{label = "Happy Dance", type = "scenario", data = {anim = "WORLD_HUMAN_STRIP_WATCH_STAND"}},
			{label = "Drinking and Dancing", type = "scenario", data = {anim = "WORLD_HUMAN_PARTYING"}},
			{label = "Black Magic", type = "anim", data = {lib = "misschinese2_crystalmazemcs1_ig", anim = "dance_loop_tao", movable = true}, isNitro = true},
			{label = "More Black Magic", type = "anim", data = {lib = "misschinese2_crystalmazemcs1_cs", anim = "dance_loop_tao", movable = true}, isStaff = true},
		}
	},
	{
		label = 'Workouts',
		items = {
			{label = "Yoga", type = "anim", data = {lib = "amb@world_human_yoga@male@base", anim = "base_a"}},
			{label = "Flex", type = "scenario", data = {anim = "WORLD_HUMAN_MUSCLE_FLEX"}},
			{label = "Situps", type = "scenario", data = {anim = "WORLD_HUMAN_SIT_UPS"}},
			{label = "Pushups", type = "scenario", data = {anim = "WORLD_HUMAN_PUSH_UPS"}},
			{label = "Twerking", type = "anim", data = {lib = "mini@strip_club@private_dance@part3", anim = "priv_dance_p3"}},
			{label = "Standing Jog", type = "scenario", data = {anim = "WORLD_HUMAN_JOG_STANDING"}},
		}
	},
	{
		label = 'Fun Stuff',
			items = {
			{label = "DJ", type = "anim", data = {lib = "anim@mp_player_intcelebrationmale@dj", anim = "dj"}},
			{label = "Selfie", type = "scenario", data = {anim = "world_human_tourist_mobile"}},
			{label = "Musician", type = "scenario", data = {anim = "WORLD_HUMAN_MUSICIAN"}},
			{label = "Hold Sign", type = "scenario", data = {anim = "WORLD_HUMAN_BUM_FREEWAY"}},
			{label = "Air Guitar", type = "anim", data = {lib = "anim@mp_player_intcelebrationmale@air_guitar", anim = "air_guitar"}},
			{label = "Serve Shots", type = "anim", data = {lib = "mini@drinking", anim = "shots_barman_b"}},
			{label = "Cook on BBQ", type = "scenario", data = {anim = "PROP_HUMAN_BBQ"}},
			{label = "Rock'n'Roll", type = "anim", data = {lib = "mp_player_int_upperrock", anim = "mp_player_int_rock"}},
			{label = "Human Statue", type = "scenario", data = {anim = "WORLD_HUMAN_HUMAN_STATUE"}},
		}
	},
	{
		label = 'Activites',
		items = {
			-- {label = "Clean", type = "scenario", data = {anim = "world_human_maid_clean"}},
			-- {label = "Fishing", type = "scenario", data = {anim = "world_human_stand_fishing"}},
			-- {label = "Read Map", type = "scenario", data = {anim = "WORLD_HUMAN_TOURIST_MAP"}},   
			{label = "Gardening", type = "scenario", data = {anim = "world_human_gardener_plant"}},
			{label = "Paparazzi", type = "scenario", data = {anim = "WORLD_HUMAN_PAPARAZZI"}},
			{label = "Binoculars", type = "scenario", data = {anim = "WORLD_HUMAN_BINOCULARS"}},
			-- {label = "Safe Cracking", type = "anim", data = {lib = "mini@safe_cracking", anim = "idle_base"}},
		}
	}
}